sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ioncretu809/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ioncretu809/docker-react npm run test -- --coverage

deploy:
  provider: elastikbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-533267337526"
  bucket_path: "frontend"
  on:
    branch: master
  acces_key_id: "$AWS_ACCESS_KEY"
  secret_acces_key: "$AWS_SECRET_KEY"

  
