sudo: required
services:
  - docker

before_install:
  - docker build  -t ioncretu809/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ioncretu809/docker-react npm run test -- --coverage
